### ISSUE TITLE
Not passing argument correctly

### ISSUE THREAD

**Issue by ye-luo** [argonne-lcf/THAPI#191]
```
OMP_NUM_THREADS=8 iprof ../../../bin/lfd -p double
Non-option arguments not allowed
usage:
  lfd [-h] [-p precision]
```
however, `-p double` was intended for lfd but didn't get passed through.
```
OMP_NUM_THREADS=8 iprof "../../../bin/lfd -p double"
```
works

**Comment by TApplencourt** [comment]
PLease use `--` so that iprof doesn't think it's a `iprof` argument. So 
`OMP_NUM_THREADS=8 iprof -- ../../../bin/lfd -p double`
Same with mpi
```
OMP_NUM_THREADS=8 mpirun -n ZZ --  iprof -- ../../../bin/lfd -p double
```
We improved the error message in a recent version.

We can try to hack the ruby parser / write our own to improve user experience, but '--' is the "normal" unix way.
